---
all:
  vars:
    ansible_user: kbadiane
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
dev:
  hosts:
    centos:
      ansible_host: 192.168.126.130
  vars:
    ansible_password: physicien
    env: developpement
web:
  hosts:
    ubuntu:
      ansible_host: 192.168.126.131
  vars:
    ansible_password: physicien
    env: webserver
